# Compiler and flags
CC = cc
CFLAGS = -Wall -Werror - Wextra

# Directories
SRC_DIR = srcs
INC_DIR = includes

SRCS = srcs/ft_putchar.c srcs/ft_putstr.c srcs/ft_strcmp.c srcs/ft_strlen.c srcs/ft_swap.c
OBJS = $(SRCS:.c=.o)